# Use variables instead to help with consistency
vars:
  - logatec:
      models: [linear, rforest, xgb, xgbrf, knn]
      #models: [knn]
      subsets: [winter, spring]
      #splits: [exclude]
      splits: [random, kfold, exclude]

# Filename templates:
# datasets: dataset-${dataset}.pkl
# models: model-${algorithm}-${dataset}-${split}.pkl
# Reports: summary-${dataset}-${split}-${algorithm}.json

# Filename templates (by ChatGPT):
# Models: models/${dataset}-${model}-${split}-${version}.pkl
# Reports: reports/${dataset}-${model}-${split}-report.json
# Datasets: processed/${dataset}.pkl
# Split indices: ???

stages:
  prepare-dataset-logatec:
    desc: Download, unzip, and convert dataset to picke format
    matrix:
      subset: ${logatec.subsets}
    cmd:
      - unzip -j data/raw/logatec-fingerprint.zip ${item.subset}_data.json -d data/raw/
      - >-
        python src/data/prepare_dataset_logatec.py
        --input data/raw/${item.subset}_data.json
        --output data/interim/logatec-${item.subset}.pkl
        --task regression
      - rm data/raw/${item.subset}_data.json
    deps:
      - src/data/prepare_dataset_logatec.py
      - data/raw/logatec-fingerprint.zip
    outs:
      - data/interim/logatec-${item.subset}.pkl

  prepare-features-logatec:
    desc: Perform feature engineering steps
    matrix:
      subset: ${logatec.subsets}
    cmd: >
      python src/data/prepare_features_logatec.py
      --input data/interim/logatec-${item.subset}.pkl
      --output data/processed/logatec-${item.subset}.pkl
      --params params.yaml
    deps:
      - src/data/prepare_features_logatec.py
      - data/interim/logatec-${item.subset}.pkl
    outs:
      - data/processed/logatec-${item.subset}.pkl

  prepare-split-logatec:
    desc: Prepare several train-test splits for model training
    matrix:
      subset: ${logatec.subsets}
      split: ${logatec.splits}
    cmd: >
      python src/data/prepare_split_logatec.py
      --input data/processed/logatec-${item.subset}.pkl
      --output-indices data/processed/logatec-${item.subset}-indices-${item.split}.pkl
      --split ${item.split}
      --params params.yaml
    params:
      - seed
      - split
    deps:
      - src/data/prepare_split_logatec.py
      - data/processed/logatec-${item.subset}.pkl
    outs:
      - data/processed/logatec-${item.subset}-indices-${item.split}.pkl

  train-logatec:
    desc: Benchmark models' performance on different subsets and splits
    matrix:
      subset: ${logatec.subsets}
      split: ${logatec.splits}
      model: ${logatec.models}

    # TODO: Add models ...
    cmd: >
      python src/models/train_regressor.py
      --data data/processed/logatec-${item.subset}.pkl
      --split-indices data/processed/logatec-${item.subset}-indices-${item.split}.pkl
      --use ${item.model}
      --params params.yaml
      --out-model models/logatec-${item.subset}-${item.model}-${item.split}.pkl
    # models/logatec-${item.subset}-${item.split}-${item.model}-evaluation.pkl
    params:
      - seed
      - models.regression
    deps:
      - src/models/train_regressor.py
      - data/processed/logatec-${item.subset}.pkl
      - data/processed/logatec-${item.subset}-indices-${item.split}.pkl
    outs:
      - models/logatec-${item.subset}-${item.model}-${item.split}.pkl
      #- models/logatec-${item.subset}-${item.split}-${item.model}-evaluation.pkl

  evaluation-logatec:
    desc: Perform evaluation of models.
    matrix:
      subset: ${logatec.subsets}
      split: ${logatec.splits}
      model: ${logatec.models}
    cmd: >
      python src/evaluation/evaluate.py
      --model models/logatec-${item.subset}-${item.model}-${item.split}.pkl
      --data data/processed/logatec-${item.subset}.pkl
      --split-indices data/processed/logatec-${item.subset}-indices-${item.split}.pkl
      --output-summary reports/logatec-${item.subset}-${item.model}-${item.split}-report.json
      --task regression
    #  --type minimal
    # --split-indices reports/logatec-${item.subset}-${item.model}-${item.split}-report.json
    # --model models/logatec-${item.subset}-${item.split}-${item.model}-evaluation.pkl
    deps:
      - src/evaluation/evaluate.py
      - models/logatec-${item.subset}-${item.model}-${item.split}.pkl
      - data/processed/logatec-${item.subset}-indices-${item.split}.pkl

    # TODO: rename metrics to summary
    metrics:
      - reports/logatec-${item.subset}-${item.model}-${item.split}-report.json:
          cache: false
    #plots:
    #  - reports/logatec/${item.model}-${item.subset}-${item.split}.png

  # visualize-logatec:
  #   desc: Visualize model performance
  #   matrix:
  #     subset: ${logatec.subsets}
  #     split: ${logatec.splits}
  #     model: ${logatec.models}
  #   cmd: >
  #     python src/visualization/visualize.py
  #     --model models/logatec-${item.subset}-${item.model}-${item.split}.pkl
  #     --data data/processed/logatec-${item.subset}.pkl
  #     --split-indices data/processed/logatec-${item.subset}-indices-${item.split}.pkl
  #     --output-summary reports/logatec-${item.subset}-${item.model}-${item.split}-report.json
  #     --task regression
