# Filename templates (by ChatGPT):
# Models: models/${dataset}-${model}-${split}-${version}.pkl
# Reports: reports/${dataset}-${model}-${split}-report.json
# Datasets: processed/${dataset}.pkl
# Split indices: ???

vars:
  - logatec:
      #models: [knn]
      subsets: [spring]
      #splits: [exclude]
      models: [linear, rforest, xgb, xgbrf, knn]
      #subsets: [winter, spring]
      #splits: [random, kfold, exclude]
      splits: [Random, KFold, LeaveOneGroupOut]

  - ctw2019:
      models: []

stages:
  prepare-dataset-logatec:
    desc: Download, unzip, and convert dataset to picke format
    matrix:
      subset: ${logatec.subsets}
    cmd:
      - unzip -j data/raw/logatec-fingerprint.zip ${item.subset}_data.json -d data/raw/
      - >-
        python src/data/prepare_dataset_logatec.py
        --input data/raw/${item.subset}_data.json
        --output data/interim/logatec-${item.subset}.pkl
        --task regression
      - rm data/raw/${item.subset}_data.json
    deps:
      - src/data/prepare_dataset_logatec.py
      - data/raw/logatec-fingerprint.zip
    outs:
      - data/interim/logatec-${item.subset}.pkl

  prepare-features-logatec:
    desc: Perform feature engineering steps
    matrix:
      subset: ${logatec.subsets}
    cmd: >
      python src/data/prepare_features_logatec.py
      --input data/interim/logatec-${item.subset}.pkl
      --output data/processed/logatec-${item.subset}.pkl
    deps:
      - src/data/prepare_features_logatec.py
      - data/interim/logatec-${item.subset}.pkl
    outs:
      - data/processed/logatec-${item.subset}.pkl

  prepare-split-logatec:
    desc: Prepare several train-test splits for model training
    matrix:
      subset: ${logatec.subsets}
      split: ${logatec.splits}
    cmd: >
      python src/data/prepare_split_logatec.py
      --input data/processed/logatec-${item.subset}.pkl
      --output-indices data/splits/logatec-${item.subset}-${item.split}.pkl
      --split ${item.split}
    params:
      - seed
      - split
    deps:
      - src/data/prepare_split_logatec.py
      - data/processed/logatec-${item.subset}.pkl
    outs:
      - data/splits/logatec-${item.subset}-${item.split}.pkl

  train-logatec:
    desc: Benchmark models' performance on different subsets and splits
    matrix:
      subset: ${logatec.subsets}
      split: ${logatec.splits}
      model: ${logatec.models}

    # TODO: Add models ...
    cmd: >
      python src/models/train_regressor.py
      --data data/processed/logatec-${item.subset}.pkl
      --split-indices data/splits/logatec-${item.subset}-${item.split}.pkl
      --use ${item.model}
      --model-output models/logatec-${item.subset}-${item.model}-${item.split}.pkl
      --best-params-output models/logatec-${item.subset}-${item.model}-${item.split}-hparams.json
    params:
      - seed
      - models.regression
    deps:
      - src/models/train_regressor.py
      - data/processed/logatec-${item.subset}.pkl
      - data/splits/logatec-${item.subset}-${item.split}.pkl
    outs:
      - models/logatec-${item.subset}-${item.model}-${item.split}.pkl
      - models/logatec-${item.subset}-${item.model}-${item.split}-hparams.json

  evaluation-logatec:
    desc: Perform evaluation of models.
    matrix:
      subset: ${logatec.subsets}
      split: ${logatec.splits}
      model: ${logatec.models}
    cmd: >
      python src/evaluation/evaluate.py
      --model models/logatec-${item.subset}-${item.model}-${item.split}.pkl
      --data data/processed/logatec-${item.subset}.pkl
      --split-indices data/splits/logatec-${item.subset}-${item.split}.pkl
      --output-summary reports/logatec-${item.subset}-${item.model}-${item.split}-report.json
      --task regression
    deps:
      - src/evaluation/evaluate.py
      - models/logatec-${item.subset}-${item.model}-${item.split}.pkl
      - data/splits/logatec-${item.subset}-${item.split}.pkl

    # TODO: rename metrics to summary
    metrics:
      - reports/logatec-${item.subset}-${item.model}-${item.split}-report.json:
          cache: false
    #plots:
    #  - reports/logatec/${item.model}-${item.subset}-${item.split}.png

  # visualize-logatec:
  #   desc: Visualize model performance
  #   matrix:
  #     subset: ${logatec.subsets}
  #     split: ${logatec.splits}
  #     model: ${logatec.models}
  #   cmd: >
  #     python src/visualization/visualize.py
  #     --model models/logatec-${item.subset}-${item.model}-${item.split}.pkl
  #     --data data/processed/logatec-${item.subset}.pkl
  #     --split-indices data/splits/logatec-${item.subset}-${item.split}.pkl
  #     --output-summary reports/logatec-${item.subset}-${item.model}-${item.split}-report.json
  #     --task regression


  prepare-dataset-ctw2019:
    desc: Prepare CTW2019 dataset from the MLOps pipeline
    cmd:
      - unzip data/raw/CTW2019_Dataset_h5.zip -d data/raw/
      - >-
        python src/data/prepare_dataset_ctw2019.py
        --data-h data/raw/h_Estimated_CTW_Train.h5
        --data-snr data/raw/SNR_CTW_Train.h5
        --data-pos data/raw/r_Position_CTW_Train.h5
        --output data/interim/ctw2019.pkl
        --task regression
      - rm data/raw/{h_Estimated,SNR,r_Position}_CTW_Train.h5
    deps:
      - data/raw/CTW2019_Dataset_h5.zip
      - src/data/prepare_dataset_ctw2019.py
    outs:
      - data/interim/ctw2019.pkl:
          cache: false

  prepare-features-ctw2019:
    desc: Prepare CTW2019 dataset
    cmd: >
      python src/data/prepare_features_ctw2019.py
      --input data/interim/ctw2019.pkl
      --output data/processed/ctw2019.pkl
    deps:
      - src/data/prepare_features_ctw2019.py
      - data/interim/ctw2019.pkl
    outs:
      - data/processed/ctw2019.pkl:
          cache: false


  prepare-split-ctw2019:
    desc: Prepare CTW2019 data split
    matrix:
      split: [KFold, Random, ShortEdge, LongEdge, Cutout]
    cmd: >
      python src/data/prepare_split_ctw2019.py
      --input data/processed/ctw2019.pkl
      --split ${item.split}
      --output-indices data/splits/ctw2019-${item.split}.pkl
    params:
      - seed
      - split
    deps:
      - data/processed/ctw2019.pkl
      - src/data/prepare_split_ctw2019.py
    outs:
      - data/splits/ctw2019-${item.split}.pkl:
          cache: false
