stages:

  # download:
  #   desc: Download dataset from authors website.
  #   cmd: |
  #     curl --insecure -o data/raw/Lumos5G-v1.0.zip https://lumos5g.umn.edu/downloads/Lumos5G-v1.0.zip
  #     unzip -j data/raw/Lumos5G-v1.0.zip Lumos5G-v1.0/Lumos5G-v1.0.csv -d data/raw/
  #     rm data/raw/Lumos5G-v1.0.zip
  #   outs:
  #     - data/raw/Lumos5G-v1.0.csv




  prepare:
    desc: Prepare Lumos5G dataset for MLOps pipeline
    cmd: |
      unzip -j data/raw/Lumos5G-v1.0.zip Lumos5G-v1.0/Lumos5G-v1.0.csv -d data/raw/
      python prepare.py --input data/raw/Lumos5G-v1.0.csv --output data/interim/lumos5g.pkl
      rm data/raw/Lumos5G-v1.0.csv
    deps:
      - data/raw/Lumos5G-v1.0.zip
      - prepare.py
    outs:
      - data/interim/lumos5g.pkl

  featurize:
    desc: Featurize dataset
    cmd: >
      python featurize.py
      --input data/interim/lumos5g.pkl
      --output data/prepared/lumos5g.pkl
    deps:
      - featurize.py
      - data/interim/lumos5g.pkl
    outs:
      - data/prepared/lumos5g.pkl

  fit:
    desc: Split dataset and store indices
    matrix:
      split: [KFold]
    cmd: >
      python split.py
      --input data/prepared/lumos5g.pkl
      --split ${item.split}
      --indices data/splits/${item.split}Split.pkl
    params:
      - split
    deps:
      - data/prepared/lumos5g.pkl
      - split.py
    outs:
      - data/splits/${item.split}Split.pkl

  benchmark:
    desc: Determine best hyper-parameters for algorithm on several CVs
    matrix:
      split: [KFold]
      algorithm: [LinearRegression, XGBRegressor, RandomForestRegressor, KNeighborsRegressor]
    cmd: >
      python ../../scripts/benchmark.py
      --use ${item.algorithm}
      --data data/prepared/lumos5g.pkl
      --split-indices data/splits/${item.split}Split.pkl
      --output-report models/reports/${item.algorithm}-${item.split}Split.pkl
    params:
      - models.${item.algorithm}
    deps:
      - ../../scripts/benchmark.py
      - data/prepared/lumos5g.pkl
      - data/splits/${item.split}Split.pkl
    outs:
      - models/reports/${item.algorithm}-${item.split}Split.pkl

  evaluation:
    cmd: >
      python ../../scripts/report.py
      models/reports/*.pkl
      --output-report reports/metrics.json
    deps:
      - ../../scripts/report.py
      - models/reports
    metrics:
      - reports/metrics.json:
          cache: false
