vars:
  - ctw2019:
      models: [LinearRegression, RandomForestRegressor, XGBRegressor, KNeighborsRegressor]
      #splits: [Random, ShortEdge, LongEdge, Cutout]
      splits: [Random]

stages:

  prepare:
    desc: Prepare CTW2019 dataset for the MLOps pipeline
    cmd:
      - unzip data/raw/CTW2019_Dataset_h5.zip -d data/raw/
      - >
        python prepare.py
        --data-h data/raw/h_Estimated_CTW_Train.h5
        --data-snr data/raw/SNR_CTW_Train.h5
        --data-pos data/raw/r_Position_CTW_Train.h5
        --output data/interim/ctw2019.pkl
      - rm data/raw/*.h5
    deps:
      - data/raw/CTW2019_Dataset_h5.zip
      - prepare.py
    outs:
      - data/interim/ctw2019.pkl

  featurize:
    desc: Prepare CTW2019 dataset
    cmd: >
      python featurize.py
      --input data/interim/ctw2019.pkl
      --output data/prepared/ctw2019.pkl
    deps:
      - featurize.py
      - data/interim/ctw2019.pkl
    outs:
      - data/prepared/ctw2019.pkl


  flatten:
    desc: Prepare CTW2019 dataset
    cmd: >
      python flatten.py
      --input data/prepared/ctw2019.pkl
      --output data/prepared/ctw2019.flatten.pkl
    deps:
      - flatten.py
      - data/prepared/ctw2019.pkl
    outs:
      - data/prepared/ctw2019.flatten.pkl


  split:
    desc: Prepare CTW2019 data split
    matrix:
      split: ${ctw2019.splits}
    cmd: >
      python split.py
      --input data/prepared/ctw2019.pkl
      --split ${item.split}
      --output-indices data/splits/${item.split}Split.pkl
    params:
      - seed
      - split
    deps:
      - data/prepared/ctw2019.pkl
      - split.py
    outs:
      - data/splits/${item.split}Split.pkl

  # benchmark:
  #   desc: Determine best hyper-parameters for algorithm on several CVs
  #   matrix:
  #     split: ${ctw2019.splits}
  #     model: ${ctw2019.models}
  #   cmd: >
  #     python train.py
  #     --use ${item.model}
  #     --data data/prepared/ctw2019.pkl
  #     --split-indices data/splits/${item.split}Split.pkl
  #     --output-report models/reports/${item.model}-${item.split}Split.pkl
  #   params:
  #     - seed
  #     - models.regression
  #   deps:
  #     - train.py
  #     - data/prepared/ctw2019.pkl
  #     - data/splits/${item.split}Split.pkl
  #   outs:
  #     - models/reports/${item.model}-${item.split}Split.pkl

  # benchmark-deeplearning:
  #   matrix:
  #     split: [Random, ShortEdge, LongEdge, Cutout]
  #     model:
  #       - name: LinearRegression
  #         inputs: data/prepared/ctw2019.flatten.pkl
  #       - name: Arnold2018DeepModel
  #         inputs: data/prepared/ctw2019.pkl
  #   cmd: >
  #     python train_deep.py
  #     --use ${item.model.name}
  #     --data ${item.model.inputs}
  #     --split-indices data/splits/${item.split}Split.pkl
  #     --output-report models/reports/${item.model}-${item.split}Split.pkl
  #   params:
  #     - seed
  #     - models.regression
  #   deps:
  #     - train_deep.py
  #     - ${item.model.inputs}
  #     - data/splits/${item.split}Split.pkl
  #   outs:
  #     - models/reports/${item.model.name}-${item.split}Split.pkl

  benchmark-deeplearning:
    matrix:
      split: ${ctw2019.splits}
      model:
        - name: Arnold2018DeepModel
          input: data/prepared/ctw2019.flatten.pkl
        - name: Arnold2019SoundingModel
          input: data/prepared/ctw2019.pkl
        - name: Pirnat2022Pirnat1G
          input: data/prepared/ctw2019.pkl
        - name: Cerar2021Localization
          input: data/prepared/ctw2019.pkl
    cmd: >
      python ../../scripts/benchmark.py
      --use ${item.model.name}
      --data ${item.model.input}
      --split-indices data/splits/${item.split}Split.pkl
      --output-report models/reports/${item.model.name}-${item.split}Split.pkl
    params:
      - seed
      - models.${item.model.name}
    deps:
      - ../../scripts/benchmark.py
      - ${item.model.input}
      - data/splits/${item.split}Split.pkl
    outs:
      - models/reports/${item.model.name}-${item.split}Split.pkl

  AutoML:
    matrix:
      split: ${ctw2019.splits}
    cmd: >
      python automl.py
      --data data/prepared/ctw2019.pkl
      --split-indices data/splits/${item.split}Split.pkl
      --output-report models/reports/autokeras-${item.split}Split.pkl
    deps:
      - automl.py
      - data/prepared/ctw2019.pkl
      - data/splits/${item.split}Split.pkl
    outs:
      - models/reports/autokeras-${item.split}Split.pkl


  evaluation:
    cmd: >
      python ../../scripts/report.py
      models/reports/*.pkl
      --output-report reports/metrics.json
    deps:
      - ../../scripts/report.py
      - models/reports
    metrics:
      - reports/metrics.json:
          cache: false
