seed: 42

split:
  n_splits: 5
  test_size: 0.20

models:
  LinearRegression:
    module: sklearn.linear_model
    class: LinearRegression
    hyperparameters:
      fit_intercept: [true, false]

  RandomForestRegressor:
    module: sklearn.ensemble
    class: RandomForestRegressor
    parameters:
      random_state: 42
      n_jobs: -1
    hyperparmeters:
      n_estimators: [10, 50, 100, 250, 400]
      max_depth: [5, 10, 30, 50, 150, 200, null]

  XGBRegressor:
    module: xgboost
    class: XGBRegressor
    parameters:
      random_state: 42
      n_jobs: -1

  XGBRFRegressor:
    module: xgboost
    class: XGBRFRegressor
    parameters:
      random_state: 42
      n_jobs: -1

  KNeighborsRegressor:
    module: sklearn.neighbors
    class: KNeighborsRegressor
    parameters:
      n_jobs: -1
    hyperparameters:
      n_neighbors: [5, 10, 15]
      weights: [uniform, distance]
      p: [1, 2, 3]
      leaf_size: [5, 10, 15, 30, 45]
      metric: [minkowski, euclidean, cosine, manhattan]


  Arnold2018DeepModel:
    module: skorch
    class: NeuralNetRegressor
    estimator:
      module: src.models
      class: Arnold2018DeepModel
    parameters:
      module__in_features: 29584 # 16*924*2+16
      module__random_state: 42

    hyperparameters:
      lr: [0.01, 0.001, 0.0001]

  Arnold2019SoundingModel:
    module: skorch
    class: NeuralNetRegressor
    estimator:
      module: src.models
      class: Arnold2019SoundingModel
    parameters:
      optimizer:
        module: torch.optim
        class: Adam
      callbacks:
        - module: skorch.callbacks
          class: EarlyStopping
      module__random_state: 42
      iterator_train__shuffle: true
      iterator_train__num_workers: 8
      optimizer__weight_decay: 0.01
      max_epochs: 100
      batch_size: 64
      device: cuda
      compile: true
    hyperparameters:
      lr: [0.01, 0.001, 0.0001]


  regression:
    # something
    seed: 42
