import click
import joblib

import pandas as pd
from pathlib import Path
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from ydata_profiling import ProfileReport
from json import loads

from src import load_data


class ExploratoryDataAnalysis:
    def __init__(self, df: pd, output_path: Path):
        self.df = df
        self.output_path = output_path


    def column_summary(self):
        summary_data = []
        
        for col_name in self.df.columns:

            col_dtype = self.df[col_name].dtype
            num_of_nulls = self.df[col_name].isnull().sum()
            num_of_non_nulls = self.df[col_name].notnull().sum()
            num_of_distinct_values = self.df[col_name].nunique()
            
            if num_of_distinct_values <= 10:
                distinct_values_counts = self.df[col_name].value_counts().to_dict()
            else:
                top_10_values_counts = self.df[col_name].value_counts().head(10).to_dict()
                distinct_values_counts = { 
                    k: v for k, 
                    v in sorted(top_10_values_counts.items(), key=lambda item: item[1], reverse=True)
                }

            summary_data.append({
                'Name': col_name.replace("_", "\_"),
                'DataType': col_dtype,
                'NumNulls': num_of_nulls,
                'NumNonNulls': num_of_non_nulls,
                'NumDistinctVals': num_of_distinct_values,
                'DistinctValCnts': distinct_values_counts
            })
    
        summary_df = pd.DataFrame(summary_data)
        return summary_df
    
    def column_stats(self):
        summary_data = []
        for col_name in self.df.columns:
            stats = self.df[col_name].describe()
            stats_obj = loads(stats.to_json().replace("%", " perc"))
            col_obj = { "Name": col_name.replace("_", "\_") }
            summary_data.append({**col_obj, **stats_obj})
       
        summary_df = pd.DataFrame(summary_data)
        return summary_df
    
    
    def column_histogram(self):
        # make sure the figures path exists
        figures_path = str(self.output_path).replace('/lumos5g.tex', '/figures/')
        Path(figures_path).mkdir(parents=True, exist_ok=True)
        figures = []

        # Identify numerical columns
        numerical_columns = self.df.select_dtypes(include=[np.number]).columns

        print(self.df.dtypes)
        # Perform univariate analysis on numerical columns
        for column in numerical_columns:
            # For continuous variables
            num_unique = len(self.df[column].unique())
            if  num_unique> 10:  # Assuming if unique values > 10, consider it continuous
                plt.figure(figsize=(8, 6))
                ax = sns.histplot(self.df[column], kde=True) # without bins = min(num_unique, 20) it get's stuck if extreme outliers are present, 20 is just an arbitrary value
                plt.title(f'Histogram of {column}')
                plt.xlabel(column)
                plt.ylabel('Frequency')
            else:  # For discrete or ordinal variables
                plt.figure(figsize=(8, 6))
                ax = sns.countplot(x=column, data=self.df)
                plt.title(f'Count of {column}')
                plt.xlabel(column)
                plt.ylabel('Count')
                
            # Annotate each bar with its count
            for p in ax.patches:
                ax.annotate(format(p.get_height(), '.0f'), 
                            (p.get_x() + p.get_width() / 2., p.get_height()), 
                            ha = 'center', va = 'center', 
                            xytext = (0, 5), 
                            textcoords = 'offset points')
                
            figpath = Path(figures_path + '' + column + '.png')
            plt.savefig(figpath)
            plt.close()
            figures.append({ "ColName": column, 
                            "Path":  Path('./figures/' + column + '.png') })
        df_figures = pd.DataFrame(figures)
        return df_figures

    def heatmap(self):
        # provide the path to save to
        figure_path = Path(str(self.output_path).replace('/lumos5g.tex', '/figures/heatmap.png'))
        
        print(self.df)
        
        # Create a correlation matrix
        corr_matrix = self.df.select_dtypes(include='number').corr()

        # Plot the heatmap
        plt.figure(figsize=(10, 8))
        sns.heatmap(corr_matrix, annot=True, cmap="coolwarm")

        # Save the heatmap to the specified output path
        plt.savefig(figure_path)
        plt.close()

    def generate_latex_document(self, dataframes, figures, output_path):
        # Add beginning of .tex
        latex_content = """
            \\documentclass{article}
            \\usepackage{graphicx}
            \\usepackage{booktabs}
            \\newcommand{\pdftitle}{EDA}
            \\begin{document}
            \\title{\pdftitle}
            \\author{Generated by Python}
            \\date{\\today}
            \\maketitle
        """.replace('           ', '')
       

        # Add tables to the .tex
        for i, (df, label, caption) in enumerate(dataframes):
            table_str = df.to_latex(index=False, 
                                    caption=caption, 
                                    label=label) \
                .replace('\n', '\n                    ')
            
            latex_content += f"""
                {table_str}
            """

        # Add figures to the .tex
        for i, row in figures.iterrows():
            path = str(row["Path"])
            caption = row["ColName"].replace("_", " ")           
            latex_content += f"""
                \\begin{{figure}}[h]
                    \\centering
                    \\includegraphics[width=0.8\\textwidth]{{{path}}}
                    \\caption{{{caption}}}
                    \\label{{fig:{i+1}}}
                \\end{{figure}}
            """

        # Add ending to the .tex
        latex_content += """
        \\end{document}
        """.replace('        ', '')

        # Write the LaTeX content to a file
        with open(output_path, 'w') as f:
            f.write(latex_content)

        print(f"LaTeX file generated at: {output_path}")


    def gen_tex_report(self):
        # generate the various sections of an EDA
        cols_summary = self.column_summary()
        cols_stats = self.column_stats()
        hist_figs = self.column_histogram()
        self.heatmap()
        

        # prepare the dataframe with heatnao details to add to thee histogram df
        mapdf = pd.DataFrame([{ "ColName": "heatmap", "Path": Path('./figures/heatmap.png') }])
        
        # generate the .tex report
        self.generate_latex_document(
            [[cols_summary, "Col summary", "Col summary"],
             [cols_stats, "Col stats", "Col stats"]], 
            pd.concat([hist_figs, mapdf], ignore_index = True),
            self.output_path)
       

@click.command()
@click.option(
    "--input",
    "input_path",
    type=click.Path(exists=True, dir_okay=False, path_type=Path),
    required=True,
)
@click.option(
    "--output",
    "output_path",
    type=click.Path(dir_okay=False, writable=True, path_type=Path),
    required=True,
)

def cli(input_path: Path, output_path: Path):
    if str(output_path).find("interim") >= 0:
        df = joblib.load(input_path)
    elif str(output_path).find("prepared") >=0:
        features, targets = load_data(input_path)
        df = pd.concat([features, targets], axis=1)
    else:
        print("!! eda not available for this input data")
    
    # generate .tex eda report
    edai = ExploratoryDataAnalysis(df, output_path)
    edai.gen_tex_report()
    
    # generate html eda report
    profile = ProfileReport(df, title="Profiling Report")
    htmlpath = str(output_path).replace('/lumos5g.tex', '/lumos5g.html')
    profile.to_file(htmlpath)
        
if __name__ == "__main__":
    cli()