# Filename templates (by ChatGPT):
# Models: models/${dataset}-${model}-${split}-${version}.pkl
# Reports: reports/${dataset}-${model}-${split}-report.json
# Datasets: processed/${dataset}.pkl
# Split indices: ???


vars:
  - logatec:
      subsets: [winter, spring]
      models: [LinearRegression, RandomForestRegressor, XGBRegressor, XGBRFRegressor, KNeighborsRegressor]
      splits: [Random, KFold, LeaveOneGroupOut]

stages:
  prepare:
    desc: Download, unzip, and convert dataset to picke format
    matrix:
      subset: ${logatec.subsets}
    cmd: |
      unzip -j data/raw/logatec.zip ${item.subset}_data.json -d data/raw/
      python prepare.py --method average --input data/raw/${item.subset}_data.json --output data/interim/${item.subset}.pkl
      rm data/raw/${item.subset}_data.json
    deps:
      - prepare.py
      - data/raw/logatec.zip
    outs:
      - data/interim/${item.subset}.pkl


  featurize:
    desc: Enrich dataset with additional features
    matrix:
      subset: ${logatec.subsets}
    cmd: >
      python featurize.py
      --input data/interim/${item.subset}.pkl
      --output data/prepared/${item.subset}.pkl
    deps:
      - featurize.py
      - data/interim/${item.subset}.pkl
    outs:
      - data/prepared/${item.subset}.pkl

  split:
    desc: Prepare train-test split indices for model training and evaluation
    matrix:
      subset: ${logatec.subsets}
      split: ${logatec.splits}
    cmd: >
      python split.py
      --input data/prepared/${item.subset}.pkl
      --split ${item.split}
      --output-indices data/splits/${item.subset}-${item.split}Split.pkl
    params:
      - seed
      - split
    deps:
      - split.py
      - data/prepared/${item.subset}.pkl
    outs:
      - data/splits/${item.subset}-${item.split}Split.pkl


  benchmark: # Should I name this "benchmark" or "optimization"
    desc: Benchmarks determine best hyper-parameters for algorithm(s)
    matrix:
      subset: ${logatec.subsets}
      split: ${logatec.splits}
      model: ${logatec.models}
    cmd: >
      python ../../scripts/benchmark.py
      --use ${item.model}
      --data data/prepared/${item.subset}.pkl
      --split-indices data/splits/${item.subset}-${item.split}Split.pkl
      --output-report models/reports/${item.subset}-${item.model}-${item.split}Split.pkl
    params:
      - seed
      - models.${item.model}
    deps:
      - ../../scripts/benchmark.py
      - data/prepared/${item.subset}.pkl
      - data/splits/${item.subset}-${item.split}Split.pkl
    outs:
      - models/reports/${item.subset}-${item.model}-${item.split}Split.pkl


  # evaluation:
  #   matrix:
  #     subset: ${logatec.subsets}
  #     split: ${logatec.splits}
  #     model: ${logatec.models}
  #   cmd: >
  #     python report.py
  #     --input reports/${item.subset}-${item.model}-${item.split}.pkl
  #     --output-report metrics/${item.subset}-${item.model}-${item.split}.json
  #   deps:
  #     - report.py
  #     - reports/${item.subset}-${item.model}-${item.split}.pkl
  #   metrics:
  #     - metrics/${item.subset}-${item.model}-${item.split}.json:
  #         cache: false

  evaluation:
    matrix:
      subset: ${logatec.subsets}
    cmd: >
      python ../../scripts/report.py
      models/reports/${item.subset}-*.pkl
      --output-report reports/metrics-${item.subset}.json
    deps:
      - ../../scripts/report.py
      - models/reports
    metrics:
      - reports/metrics-${item.subset}.json:
          cache: false


  # evaluation:
  #   desc: Perform evaluation of models.
  #   matrix:
  #     subset: ${logatec.subsets}
  #     split: ${logatec.splits}
  #     model: ${logatec.models}
  #   cmd: >
  #     python ../../scripts/evaluate.py
  #     --model models/${item.subset}-${item.model}-${item.split}.pkl
  #     --data data/prepared/${item.subset}.pkl
  #     --split-indices data/splits/${item.subset}-${item.split}.pkl
  #     --output-summary reports/${item.subset}-${item.model}-${item.split}.json
  #     --task regression
  #   deps:
  #     - ../../scripts/evaluate.py
  #     - models/${item.subset}-${item.model}-${item.split}.pkl
  #     - data/prepared/${item.subset}.pkl
  #     - data/splits/${item.subset}-${item.split}.pkl
  #     - reports/${item.subset}-${item.model}-${item.split}.json

  # summary:
  #   matrix:
  #     subset: ${logatec.subsets}
  #   cmd: python report.py reports/${item.subset}-*.json
  #   deps:
  #     - reports/${item.subset}-*.json
  #     - report.py
  #   metrics:
  #     - summary.json


    # TODO: rename metrics to summary
    #metrics:
    #  - reports/${item.subset}-${item.model}-${item.split}.json:
    #      cache: false
    #plots:
    #  - reports/logatec/${item.model}-${item.subset}-${item.split}.png







  # report:
  #   desc: Build report for all trained models
  #   cmd: >
  #     python ../../scripts/report.py
  #     --input-folder reports/
  #     --output evaluation/metrics.json
  #   deps:
  #     - reports/
  #     - ../../scripts/report.py
  #   metrics:
  #     - evaluation/metrics.json



  # evaluation-logatec:
  #   desc: Perform evaluation of models.
  #   matrix:
  #     subset: ${logatec.subsets}
  #     split: ${logatec.splits}
  #     model: ${logatec.models}
  #   cmd: >
  #     python src/evaluation/evaluate.py
  #     --model models/logatec-${item.subset}-${item.model}-${item.split}.pkl
  #     --data data/processed/logatec-${item.subset}.pkl
  #     --split-indices data/splits/logatec-${item.subset}-${item.split}.pkl
  #     --output-summary reports/logatec-${item.subset}-${item.model}-${item.split}-report.json
  #     --task regression
  #   deps:
  #     - src/evaluation/evaluate.py
  #     - models/logatec-${item.subset}-${item.model}-${item.split}.pkl
  #     - data/splits/logatec-${item.subset}-${item.split}.pkl

  #   # TODO: rename metrics to summary
  #   metrics:
  #     - reports/logatec-${item.subset}-${item.model}-${item.split}-report.json:
  #         cache: false
  #   #plots:
  #   #  - reports/logatec/${item.model}-${item.subset}-${item.split}.png

  # # visualize-logatec:
  # #   desc: Visualize model performance
  # #   matrix:
  # #     subset: ${logatec.subsets}
  # #     split: ${logatec.splits}
  # #     model: ${logatec.models}
  # #   cmd: >
  # #     python src/visualization/visualize.py
  # #     --model models/logatec-${item.subset}-${item.model}-${item.split}.pkl
  # #     --data data/processed/logatec-${item.subset}.pkl
  # #     --split-indices data/splits/logatec-${item.subset}-${item.split}.pkl
  # #     --output-summary reports/logatec-${item.subset}-${item.model}-${item.split}-report.json
  # #     --task regression


  # prepare-dataset-ctw2019:
  #   desc: Prepare CTW2019 dataset from the MLOps pipeline
  #   cmd:
  #     - unzip data/raw/CTW2019_Dataset_h5.zip -d data/raw/
  #     - >-
  #       python src/data/prepare_dataset_ctw2019.py
  #       --data-h data/raw/h_Estimated_CTW_Train.h5
  #       --data-snr data/raw/SNR_CTW_Train.h5
  #       --data-pos data/raw/r_Position_CTW_Train.h5
  #       --output data/interim/ctw2019.pkl
  #       --task regression
  #     - rm data/raw/{h_Estimated,SNR,r_Position}_CTW_Train.h5
  #   deps:
  #     - data/raw/CTW2019_Dataset_h5.zip
  #     - src/data/prepare_dataset_ctw2019.py
  #   outs:
  #     - data/interim/ctw2019.pkl:
  #         cache: false

  # prepare-features-ctw2019:
  #   desc: Prepare CTW2019 dataset
  #   cmd: >
  #     python src/data/prepare_features_ctw2019.py
  #     --input data/interim/ctw2019.pkl
  #     --output data/processed/ctw2019.pkl
  #   deps:
  #     - src/data/prepare_features_ctw2019.py
  #     - data/interim/ctw2019.pkl
  #   outs:
  #     - data/processed/ctw2019.pkl:
  #         cache: false


  # prepare-split-ctw2019:
  #   desc: Prepare CTW2019 data split
  #   matrix:
  #     split: [KFold, Random, ShortEdge, LongEdge, Cutout]
  #   cmd: >
  #     python src/data/prepare_split_ctw2019.py
  #     --input data/processed/ctw2019.pkl
  #     --split ${item.split}
  #     --output-indices data/splits/ctw2019-${item.split}.pkl
  #   params:
  #     - seed
  #     - split
  #   deps:
  #     - data/processed/ctw2019.pkl
  #     - src/data/prepare_split_ctw2019.py
  #   outs:
  #     - data/splits/ctw2019-${item.split}.pkl:
  #         cache: false
