seed: 42

split:
  n_splits: 5
  test_size: 0.10

models:
  LinearRegression:
    module: sklearn.linear_model
    class: LinearRegression
    hyperparameters:
      fit_intercept: [true, false]

  RandomForestRegressor:
    module: sklearn.ensemble
    class: RandomForestRegressor
    parameters:
      random_state: 42
    hyperparameters:
      n_estimators: [10, 50, 100, 250, 400]
      max_depth: [5, 10, 30, 50, 150, 200, null]

  XGBRegressor:
    module: xgboost
    class: XGBRegressor
    parameters:
      random_state: 42
      enable_categorical: true

  XGBRFRegressor:
    module: xgboost
    class: XGBRFRegressor
    parameters:
      random_state: 42
      enable_categorical: true

  KNeighborsRegressor:
    module: sklearn.neighbors
    class: KNeighborsRegressor
    #parameters:
    # n_jobs: 8
    hyperparameters:
      n_neighbors: [3, 5, 10]
      weights: [uniform, distance]
      p: [1, 2]
      leaf_size: [5, 10, 15, 30]
      metric: [minkowski, euclidean]
