seed: 42

split:
  n_splits: 5
  test_size: 0.20

models:
  LinearRegression:
    module: sklearn.linear_model
    class: LinearRegression
    hyperparameters:
      fit_intercept: [true, false]


  RandomForestRegressor:
    module: sklearn.ensemble
    class: RandomForestRegressor
    parameters:
      random_state: 42
      n_jobs: -1
    hyperparmeters:
      n_estimators: [10, 50, 100, 250, 400]
      max_depth: [5, 10, 30, 50, 150, 200, null]

  XGBRegressor:
    module: xgboost
    class: XGBRegressor
    parameters:
      random_state: 42
      n_jobs: -1

  XGBRFRegressor:
    module: xgboost
    class: XGBRFRegressor
    parameters:
      random_state: 42
      n_jobs: -1

  KNeighborsRegressor:
    module: sklearn.neighbors
    class: KNeighborsRegressor
    parameters:
      n_jobs: -1
    hyperparameters:
      n_neighbors: [5, 10, 15]
      weights: [uniform, distance]
      p: [1, 2, 3]
      leaf_size: [5, 10, 15, 30, 45]
      metric: [minkowski, euclidean, cosine, manhattan]
